			<div class="left-content">
	
				<ul>
					<li class="header">Browse Market </li> 
					<li><a href="http://vietnamsuperpage.com/admin/location"><span>Location </span></a></li>
					<li><a href="http://vietnamsuperpage.com/admin/sb_category"><span>Category</span></a></li>
					<li><a href="http://vietnamsuperpage.com/admin/sb_classified_ad_type"><span>Classifieds Type</span></a></li>
				  </ul>	
				  <ul>
					<li class="header">VietNamSuperPage</li> 
					<li><a href="http://vietnamsuperpage.com/admin/livetv"><span>Live TV</span></a></li>
					<li><a href="http://vietnamsuperpage.com/admin/livetv/item"><span>Item TV</span></a></li>
					<li><a href="http://vietnamsuperpage.com/admin/artist"><span>Media manager</span></a></li>
				  </ul>
				  
			<!-- END class="left-content" -->
			</div>		