<?= $this->render("user/_header.phtml"); ?>

<form action="<?= $this->currentControllerUrl; ?>/delete-all" id="frmData" name="frmData" method="POST" onsubmit="return CheckDeleteAll();">

<div align="right" class="box-content">
	<input type="button" onclick="location.href = '<?= $this->currentControllerUrl; ?>/add';" value="<?= $this->getTranslation('Add New'); ?>" class="btn_submit_green add_act"/>
	<input type="submit" value="Delete" name="" id="" class="btn_submit_green delete_act"/>
</div>

<div class="box-content">

	<table id="show_data" width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr>
		<th width="2%" align="center"><input id="checkboxAll" name="checkboxAll" onclick="doCheckAll(document.frmData);" type="checkbox"></th>
		<th width="20%"><?= $this->firstNameTX ?></th>
		<th width="20%"><?= $this->lastNameTX ?></th>
		<th width="20%"><?= $this->emailTX ?></th>
		<th width="20%"><?= $this->roleTX ?></th>
		<th align=""><?= $this->lastLoginTX ?></th>
		<th width="6%"><?= $this->getTranslation("Action"); ?></a></th>
	</tr>
	<?
		$i=1;
		foreach($this->rsUser as $rowUser) :
	?>
		<tr class="<?= ($i==1)?' rowBlue_01':'rowBlue_02'; ?>">
			<td align="center">
				<input id="checkbox" name="checkbox[]" value="<?= $rowUser->user_id; ?>" onclick="doCheckOne(document.frmData);" type="checkbox"> 
			</td>
			<td><?= $this->h($rowUser->first_name); ?></td>
			<td><?= $this->h($rowUser->last_name); ?></td>
			<td><?= $rowUser->email; ?></td>
			<td><?= $this->h($rowUser->findParentRow('Model_Groups')->group_name); ?></td>
			<td align="center"><?= $this->RenderDate($rowUser->last_login,"d-m-Y h:i:s"); ?></td>
			<td align="center">
				<?= $this->renderStatusLink($rowUser->user_id,$this->currentControllerUrl . '/switch-status/id/' . $rowUser->user_id,$rowUser->active); ?>
				<?= $this->renderEditLink($this->currentControllerUrl . '/edit/id/' . $rowUser->user_id); ?>
				<?= $this->renderDeleteLink($this->currentControllerUrl . '/delete/id/' . $rowUser->user_id); ?>
			</td>
		</tr>
						
	<? 
			$i=-$i;
		endforeach;
	?>			
	</table>		

</div>


</form>