<? echo $this->render("tax-rate/_header.phtml"); ?>

<form action="<?= $this->currentControllerUrl; ?>/delete-all" id="frmData" name="frmData" method="POST" onsubmit="return CheckDeleteAll();">

<div align="right" class="box-content">
	<input type="button" value="  Add New  " name="" id="" class="btn_submit_green page_act" onclick="javascript:location.href = '<?= $this->currentControllerUrl; ?>/add';"/>
	<input type="submit" value="Delete" name="" id="" class="btn_submit_green delete_act"/>
</div>

<div class="box-content">

	<table id="show_data" width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr>
		<th width="2%" align="center"><input id="checkboxAll" name="checkboxAll" onclick="doCheckAll(document.frmData);" type="checkbox"></th>
		<th width="20%"><?= $this->nameTX ?></th>
		<th width="11%"><?= $this->taxRateTX ?></th>
		<th width="">Description</th>
		<th width="11%">Action</a></th>
	</tr>
	<?
		$i=1;
		foreach($this->rsTaxRates as $rowTaxRate) :
	?>
		<tr class="<?= ($i==1)?' rowBlue_01':'rowBlue_02'; ?>">
			<td align="center">
				<input id="checkbox" name="checkbox[]" value="<?= $rowTaxRate->tax_rate_id; ?>" onclick="doCheckOne(document.frmData);" type="checkbox"> 
			</td>
			<td><?= $this->h($rowTaxRate->name); ?></td>
			<td align="center"><?= $rowTaxRate->tax_rate; ?></td>
			<td><?= $this->h($rowTaxRate->description); ?></td>
			<td align="center">
				<?= $this->renderStatusLink($rowTaxRate->tax_rate_id,$this->currentControllerUrl . '/switch-status/id/' . $rowTaxRate->tax_rate_id,$rowTaxRate->active,false); ?>			
				<?= $this->renderEditLink($this->currentControllerUrl . '/edit/id/' . $rowTaxRate->tax_rate_id); ?>
				<?= $this->renderDeleteLink($this->currentControllerUrl . '/delete/id/' . $rowTaxRate->tax_rate_id); ?>
			</td>
		</tr>
	<? 
			$i=-$i;
		endforeach;
	?>			
	</table>		

</div>

</form>

