<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<? echo $this->headTitle(); ?>
<? echo $this->jQuery(); ?>
<? echo $this->headLink(); ?>
<? echo $this->headScript(); ?>

</head>
<body>

<div id="wrapper">

	<table id="page-body" width="100%" border="0" cellpadding="0" cellspacing="0">
	<tr class="page_content">
	
		<td id="right">
			<div class="right-content"  style="min-height:595px;">
				<div class="box-content">
				
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1">Elements Link</a></li>
			<li><a href="#tabs-2">Contents Link</a></li>
			<li><a href="#tabs-3">External Link</a></li>
		</ul>
		
		<div id="tabs-1">
			<div id='container_content'></div>
		</div>
		
		<div id="tabs-2">
			<? echo $this->render("element-link/_contents_link.phtml"); ?>
		</div>
		
		<div id="tabs-3">
			<? echo $this->render("element-link/_external_link.phtml"); ?>
		</div>		
	</div>				
				
				
				</div>						
			<!-- END class="right-content" -->
			</div>		
		<!-- END id="right" -->			  
		</td>
		
	<!-- END class="page_content" -->		
	</tr>
	<!-- END id="page-body" -->
	</table>	
	
<!-- END id="wrapper" -->
</div>

<div id='waiting'></div>

<script language="JavaScript">

$(document).ready(function(){
	$("#tabs").tabs();
	loadContainerData('container_content','<?= $this->currentModuleUrl ?>/element-link/ajax-element-link/admin/<?= $this->isAdmin; ?>');
});

</script>



</body>
</html>