<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount): ?>
<div class="pagination">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
	<a class="previous" href="javascript:void(0);" onclick="loadContainerData('container_content','<?php echo $this->url(array('page' => $this->previous)); ?>');">
		« <?= $this->getTranslation('Previous'); ?>
	</a>  
<?php else: ?>
  	<span class="off">« <?= $this->getTranslation('Previous'); ?></span>
<?php endif; ?>


<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="javascript:void(0);" onclick="loadContainerData('container_content','<?php echo $this->url(array('page' => $page)); ?>');">
        <?php echo $page; ?>
    </a>
  <?php else: ?>
    <span class="active"><?php echo $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>


<!-- Next page link -->
<?php if (isset($this->next)): ?>
	<a class="next" href="javascript:void(0);" onclick="loadContainerData('container_content','<?php echo $this->url(array('page' => $this->next)); ?>');">
		<?= $this->getTranslation('Next'); ?> »
	</a>  
<?php else: ?>
	<span class="off"><?= $this->getTranslation('Next'); ?> »</span>
<?php endif; ?>
</div>
<?php endif; ?>