		<div id="cpanel_item">
			<div class="icon">
				<a href="<?= BASE_URL . $this->rowMenu->admin_menu_link; ?>">
					<img border="0" align="middle" title="<?= $this->h($this->rowMenu->name); ?>" alt="<?= $this->h($this->rowMenu->name); ?>" src="<?= BASE_URL ?>/images/large_icons/<?= $this->rowMenu->admin_menu_img; ?>"/>
					<span style="font-size: 11px;"><?= $this->h($this->rowMenu->name); ?></span>
				</a>
			</div>
		</div>
		
