<table id="table_form" width="100%" border="0" cellpadding="0" cellspacing="1" >
			
<?php
	echo $this->FormRow("Available :",$this->formCheckbox('active', intval($this->rowProduct->active)));
	echo $this->FormRow("Product Name :",$this->formText('name',$this->h($this->rowProduct->name,'edit'),array('class'=>'required','size'=>60)),true);
	echo $this->FormRow("Model :",$this->formText('model',$this->h($this->rowProduct->name,'edit'),array('class'=>'required','size'=>60)),true);
	echo $this->FormRow("Manufacturer :",$this->selManufacturer);
	
	$varOptions = array();
	$varOptions[1] = $this->t('Yes');
	$varOptions[0] = $this->t('No');
	echo $this->FormRow("Product is Free :",$this->formRadio('is_free', $this->rowProduct->is_free, null, $varOptions, "&nbsp;&nbsp;"));
	echo $this->FormRow("Product is Call for Price :",$this->formRadio('is_call', $this->rowProduct->is_call, null, $varOptions, "&nbsp;&nbsp;"));
	echo $this->FormRow("Product Priced by Attributes: :",$this->formRadio('is_free', $this->rowProduct->is_free, null, $varOptions, "&nbsp;&nbsp;"));
	
?>
<!--				<tr>
					<td class="rowBlue_02 align_top"><label>Description :</label></td>
					<td class="rowBlue_01">
						<?php $this->FckEditor('description', $this->rowProduct->description, 200, '100%', true); ?>
					</td>
				</tr>
-->			
				
			<?php 
				echo $this->FormRow("Order :",$this->formText('order',$this->rowProduct->order,array('size'=>5)));				
				
			?>				
			
			</table>

			
<script language="javascript">
<!--
var tax_rates = new Array();
tax_rates["1"] = 0;

function doRound(x, places) {
  return Math.round(x * Math.pow(10, places)) / Math.pow(10, places);
}

function getTaxRate() {
  var selected_value = document.forms["new_product"].products_tax_class_id.selectedIndex;
  var parameterVal = document.forms["new_product"].products_tax_class_id[selected_value].value;

  if ( (parameterVal > 0) && (tax_rates[parameterVal] > 0) ) {
    return tax_rates[parameterVal];
  } else {
    return 0;
  }
}

function updateGross() {
  var taxRate = getTaxRate();
  var grossValue = document.forms["new_product"].products_price.value;

  if (taxRate > 0) {
    grossValue = grossValue * ((taxRate / 100) + 1);
  }

  document.forms["new_product"].products_price_gross.value = doRound(grossValue, 4);
}

function updateNet() {
  var taxRate = getTaxRate();
  var netValue = document.forms["new_product"].products_price_gross.value;

  if (taxRate > 0) {
    netValue = netValue / ((taxRate / 100) + 1);
  }

  document.forms["new_product"].products_price.value = doRound(netValue, 4);
}
//-->
</script>
			