<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Administration Control Panel</title>

<?php echo $this->jQuery(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

</head>
<body>
	<div id="wrapper">
		<div id="page-header" ><h1>Administration Control Panel</h1></div>
		<div id="page-body" align="center">
		
			<div style="padding:10px 0px;">
				<? echo $this->RenderAlert(); ?>
			</div>		
		
			<? echo $this->layout()->content; ?>
		</div>
		<? echo $this->RenderAdminFooter(); ?>
	</div>	
</body>
</html>


