<? echo $this->render("parameter/_header.phtml"); ?>

<form action="<?= $this->currentControllerUrl; ?>/delete-all" id="frmData" name="frmData" method="POST" onsubmit="return CheckDeleteAll();">

<div align="right" class="box-content">
	<input type="button" onclick="location.href = '<?= $this->currentControllerUrl; ?>/add';" value="<?= $this->getTranslation('Add New'); ?>" class="btn_submit_green add_act"/>
	<input type="submit" value="Delete" class="btn_submit_green delete_act"/>
</div>

<div class="box-content">

	<table id="show_data" width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr>
		<th width="2%" align="center"><input id="checkboxAll" name="checkboxAll" onclick="doCheckAll(document.frmData);" type="checkbox"></th>
		<th width="30%"><?= $this->nameTX ?></th>
		<th width=""><?= $this->valueTX ?></th>
		<th width="6%"><?= $this->getTranslation('Action'); ?></a></th>
	</tr>
	<?
		$i=1;
		foreach($this->rsParams as $rowParam) :
	?>
		<tr class="<?= ($i==1)?' rowBlue_01':'rowBlue_02'; ?>">
			<td align="center">
				<input id="checkbox" name="checkbox[]" value="<?= $rowParam->parameter_id; ?>" onclick="doCheckOne(document.frmData);" type="checkbox"> 
			</td>
			<td><?= $rowParam->name; ?></td>
			<td><?= $rowParam->value; ?></td>
			<td align="center">
				<?= $this->renderStatusLink($rowParam->parameter_id,$this->currentControllerUrl . '/switch-status/id/' . $rowParam->parameter_id,$rowParam->active); ?>
				<?= $this->renderEditLink($this->currentControllerUrl . '/edit/id/' . $rowParam->parameter_id); ?>
				<?= $this->renderDeleteLink($this->currentControllerUrl . '/delete/id/' . $rowParam->parameter_id); ?>
			</td>
		</tr>
						
	<? 
			$i=-$i;
		endforeach;
	?>			
	</table>		

</div>

<div class="box-content" >
	<?= $this->strPaging; ?>
</div>


</form>

