<? echo $this->render("group/_header.phtml"); ?>

<form action="<?= $this->currentControllerUrl; ?>/delete-all" id="frmData" name="frmData" method="POST" onsubmit="return CheckDeleteAll();">

<div align="right" class="box-content">
	<input type="button" onclick="location.href = '<?= $this->currentControllerUrl; ?>/add';" value="<?= $this->getTranslation('Add New'); ?>" class="btn_submit_green add_act"/>	
	<input type="submit" value="Delete" name="" id="" class="btn_submit_green delete_act"/>
</div>

<div class="box-content">

	<table id="show_data" width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr>
		<th width="2%" align="center"><input id="checkboxAll" name="checkboxAll" onclick="doCheckAll(document.frmData);" type="checkbox"></th>
		<th width="50%"><?= $this->nameTX ?></th>
		<th width=""><?= $this->roleTX ?></th>
		<th width="" align="center"><?= $this->levelTX ?></th>
		<th width="6%">Action</a></th>
	</tr>
	<?
		$i=1;
		foreach($this->rsGroups as $rowGroup) :
	?>
		<tr class="<?= ($i==1)?' rowBlue_01':'rowBlue_02'; ?>">
			<td align="center">
				<input id="checkbox" name="checkbox[]" value="<?= $rowGroup->group_id; ?>" onclick="doCheckOne(document.frmData);" type="checkbox"> 
			</td>
			<td><?= $rowGroup->group_name; ?></td>
			<td><?= $rowGroup->role; ?></td>
			<td><?= $rowGroup->level; ?></td>
			<td align="center">
				<?= $this->renderEditLink($this->currentControllerUrl . '/edit/id/' . $rowGroup->group_id); ?>
				<?= $this->renderDeleteLink($this->currentControllerUrl . '/delete/id/' . $rowGroup->group_id); ?>
			</td>
		</tr>
						
	<? 
			$i=-$i;
		endforeach;
	?>			
	</table>		

</div>



</form>

