<div id="page-header">
	<ul id='current-user'>
    	<li>Current User : 
    		<a href='<?= BASE_URL ?>/admin/user/edit/id/<?= $this->header['currentUser']->user_id; ?>'>
    			<?= $this->header['currentUser']->first_name . " " . $this->header['currentUser']->last_name ?>
   			</a>
   		</li>
        <li>Role : <?= $this->header['currentUser']->role; ?></li>
        <li>[<a href='<?= BASE_URL ?>/admin/auth/logout'>Log Out</a>]</li>
	</ul>
</div>